#!/usr/bin/env bash

HEIGHT=12
WIDTH=64
CHOICE_HEIGHT=4
BACKTITLE="Feed Opener"
TITLE="Choose a method of opening the news/feed/reddit post"
MENU="Launch with..."

OPTIONS=(1 "[Open in w3m]"
         2 "[Open in w3m with readable]"
         3 "[Open in Firefox]"
         )

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
          echo "Opening in w3m"
          w3m "$1"
          ;;
        2)
          echo "Opening in w3m, going through readable"
          readable "$1" | w3m -T text/html
	  # https://gitlab.com/gardenappl/readability-cli
	  # sudo npm -g install readability-cli
          ;;
        3)
          echo "Opening in Firefox"
          firefox "$1" &
          ;;
esac
